(() => {
  "use strict";
  const TYPES = ["HEALTH_CHECK", "CREATE_JOB", "GET_JOB", "CANCEL_JOB", "CACHE_GET", "CACHE_CLEAR", "SETTINGS_GET", "SETTINGS_UPDATE", "DIAGNOSTICS_GET", "ASSISTANT_PANEL", "ASSISTANT_PERMISSION", "ASSISTANT_LOCAL_ENABLE", "ASSISTANT_INGEST", "ASSISTANT_BINDINGS_GET", "ASSISTANT_BINDINGS_SAVE"];
  globalThis.WTProtocol = Object.freeze({ API_VERSION: 2, EXTENSION_VERSION: "0.2.0", TYPES: Object.freeze(TYPES), isKnown: (type) => TYPES.includes(type) });
})();
